server.port=8080
server.staticDir=/static
server.staticFile=index.html
server.entryPoint=home
server.storage=./

socket.port=9191

container.basePath=/home/browxy
container.mavenRepoPath=/home/browxy/.m2
container.mavenSettingsPath=/home/browxy/.m2/settings.xml

 
# jdbc:mysql://db_app:3306/test_db
datasource.url=jdbc:mysql://172.0.0.3:3306/test_db  
datasource.userName=user
datasource.password=pass