package com.browxy.wrapper.webServer.db.embedded;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;

import org.hsqldb.Server;
import org.hsqldb.persist.HsqlProperties;

import com.browxy.wrapper.webServer.config.Config;
import com.browxy.wrapper.webServer.db.DBManager;

public class HSQLDBManager {

	public static void startDatabaseServer() {
		Config config = Config.getInstance();
		Thread dbThread = new Thread(() -> {
			try {
				System.out.println("Starting HSQLDB Server...");

				HsqlProperties hsqlProperties = new HsqlProperties();
				hsqlProperties.setProperty("server.database.0", "file:" + config.getDataSourceFilePath());
				hsqlProperties.setProperty("server.dbname.0", config.getDataSourceDbName());
				hsqlProperties.setProperty("server.port", config.getDatasourceEmbeddedPort());
				hsqlProperties.setProperty("sql.case_sensitive", "true");
				
				Server server = new Server();
				server.setProperties(hsqlProperties);
				server.setLogWriter(null);
				server.setErrWriter(null);
				server.start();

				System.out.println("HSQLDB Server started on port 9001");

				initializeDatabase(config);

			} catch (Exception e) {
				e.printStackTrace();
				throw new RuntimeException("Failed to start HSQLDB Server.");
			}
		});

		dbThread.setDaemon(true);
		dbThread.start();
	}

	public static void initializeDatabase(Config config) {
		try {
			DBManager dbManager = DBManager.getInstance(config.getDataSourceUserName(), config.getDataSourcePassword(),
					config.getDataSourceUrl(!config.isDatasourceEmbedded() ? "jdbc:mysql" : "jdbc:hsqldb", "UTF-8"),
					config.getDataSourceDbName());
			
			String scriptFilePath = config.getContainerBasePath() + File.separator + "metadata" + File.separator + "init.sql";
			
			if(new File(scriptFilePath).exists()) {
			  executeSqlScript(dbManager, scriptFilePath);
			}
			
			System.out.println("Database initialized successfully.");
		} catch (SQLException | IOException e) {
			e.printStackTrace();
			throw new RuntimeException("Failed to initialize the database.");
		}
	}

	 private static void executeSqlScript(DBManager dbManager, String scriptFilePath) throws IOException, SQLException {
	        try (BufferedReader reader = new BufferedReader(new FileReader(scriptFilePath))) {
	            StringBuilder sql = new StringBuilder();
	            String line;

	            while ((line = reader.readLine()) != null) {
	                line = line.trim();
	                if (!line.isEmpty() && !line.startsWith("--")) { 
	                    sql.append(line).append(" ");
	                    if (line.endsWith(";")) {  
	                        dbManager.genericExecute("from_script", sql.toString(), new String[] {}, false);
	                        sql.setLength(0);
	                    }
	                }
	            }
	        }
	    }
	/* 
	public static boolean createUser(DBManager dbManager, String email, String password, boolean isAdmin) {		
		String checkQuery = "SELECT COUNT(*) FROM \"bxy_users\" WHERE \"email\" = ?";
	    String[] checkParams = { email };

	    try {
	        String countResult = dbManager.genericSelectSingleValue("Check_User", checkQuery, checkParams, false);
	        int count = countResult != null ? Integer.parseInt(countResult) : 0;

	        if (count > 0) {
	            return false; 
	        }

	        String insertQuery = "INSERT INTO \"bxy_users\" (\"email\", \"password\", \"isAdmin\") VALUES (?, ?, ?)";
	        String[] insertParams = { email, password, String.valueOf(isAdmin) };
	        return dbManager.genericExecute("Create_User", insertQuery, insertParams, false);
	    } catch (Exception e) {
	        e.printStackTrace();
	        return false;
	    }
	}
	*/
	 /*	
 	Map<String, String> columns = new LinkedHashMap<>();
		columns.put("id", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
		columns.put("email", "VARCHAR(255) NOT NULL UNIQUE");
		columns.put("password", "VARCHAR(255) NOT NULL");
		columns.put("isAdmin", "BOOLEAN DEFAULT false");

		Map<String, String> foreignKeys = new HashMap<>();

		dbManager.createTableForHSQL("bxy_users", columns, foreignKeys);
    
		createUser(dbManager, "bxy@bxy.com", "admin", true);
		*/
 
}
